
services:
  postgres:
    image: postgres:15
    container_name: docker_manager_db
    environment:
      POSTGRES_DB: docker_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  

volumes:
  postgres_data: